### ISSUE TITLE
If the Sublime Text setting close_windows_when_empty is true, the current window closes, if empty

### ISSUE THREAD

**Issue by evandrocoan** [FichteFoll/FileHistory#46]
1. ![image](https://user-images.githubusercontent.com/5332158/40283175-6613aa40-5c50-11e8-8759-034945c3f1d4.png)

1. ![image](https://user-images.githubusercontent.com/5332158/40283166-54f91272-5c50-11e8-9355-86aa6eb0ecc1.png)

1. Current window closed

Demonstration:

![back1](https://user-images.githubusercontent.com/5332158/45598646-cdeed280-b9b5-11e8-8824-e5df088ea7de.gif)

**Comment by FichteFoll** [comment]
This seems most likely like a limitation on ST's side. I don't see a proper way to circumvent this from the side of File History.
