### ISSUE TITLE
Don't keep redundant symlinked paths

### ISSUE THREAD

**Issue by reagle** [FichteFoll/FileHistory#48]
I often have redundant entries for the real and symlinked paths to a file. I recently added one of the paths to `path_exclude_patterns` but then sometimes miss entries.  This could easily be resolved by way of only storing paths normalized by `pathlib.Path.absolute()`.

**Comment by FichteFoll** [comment]
Counter argument: What if you wanted to edit/find the file under its symlinked name instead of the resolved file path?

**Comment by reagle** [comment]
I sympathize with that as I use symlinks to shorten long paths, especially to encrypted/mounted volumes. I'd be happy if you displayed the shortest version encountered in the pallette. 

You could easily implement by resolving a path to its canonical/absolute form and keeping a lookup dictionary of `{absolute_path: shortest_encountered path}`.

**Comment by FichteFoll** [comment]
I believe you are simplifying this to your use case. There are situations where your desired functionality isn't desired, but I can also see your use case.

I could definitely see a point in making this an option, but I have to admit I won't find time to look into implementing this myself soon. Pull requests welcome, though.

**Comment by reagle** [comment]
How do you recommend copying with redundant entries from symlinks?

**Comment by reagle** [comment]
Could be as simple as this to start with?

```
diff --git a/file_history.py b/file_history.py
index 0685dc9..6471625 100644
--- a/file_history.py
+++ b/file_history.py
@@ -1,6 +1,7 @@
 import os
 import hashlib
 import json
+import os
 import time
 import re
 import shutil
@@ -82,6 +83,7 @@ class FileHistory(with_metaclass(Singleton)):
         self.HISTORY_FILE = os.path.normpath(os.path.join(sublime.packages_path(), history_path))

         self.USE_MONOSPACE = self.__ensure_setting('monospace_font', False)
+        self.USE_ABSOLUTE_PATH = self.__ensure_setting('absolute_path', False)

         self.TIMESTAMP_SHOW = self.__ensure_setting('timestamp_show', True)
         self.TIMESTAMP_FORMAT = self.__ensure_setting('timestamp_format', self.DEFAULT_TIMESTAMP_FORMAT)
@@ -317,7 +319,10 @@ class FileHistory(with_metaclass(Singleton)):
             return

         # Only keep track of files that have a filename
-        filename = view.file_name()
+        if self.USE_ABSOLUTE:
+            filename = os.path.abspath(view.file_name())
+        else:
+            filename = view.file_name()
         if filename is not None:
             project_name = self.get_current_project_key()
```

**Comment by reagle** [comment]
Thanks. #45 doesn't look like it would be too hard, but you said you were planning a re-write?

**Comment by FichteFoll** [comment]
Yeah, the package is currently in full maintenance mode. I didn't even wrote the initial code myself and don't agree with many of the coding choices, but a rewrite takes quite a bit of time that I don't have to spare at the moment.

However, I am still willing to review pull requests or implement bug fixes.
